disabled_rules: # rule identifiers to exclude from running
  - colon
  - comma
  - function_parameter_count
  - switch_case_alignment
  - todo
  - nesting
  - implicit_getter
  - multiple_closures_with_trailing_closure
  - xctfail_message
  - unneeded_break_in_switch
  - is_disjoint
  - class_delegate_protocol
  - redundant_discardable_let
  - redundant_optional_initialization
  - unused_closure_parameter
  - legacy_constructor
  - control_statement
  - trailing_whitespace
  - identifier_name
  - statement_position
  - unused_optional_binding
  - function_body_length
opt_in_rules: # some rules are only opt-in
  - empty_count
  # Find all the available rules by running:
  # swiftlint rules
#included: # paths to include during linting. `--path` is ignored if present.
  - Source
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  - WeatherAppTests

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
force_cast: warning # implicitly
force_try:
  severity: warning # explicitly
# rules that have both warning and error levels, can set just the warning level
# implicitly
line_length: 300
# they can set both implicitly with an array
type_body_length:
  - 500 # warning
  - 600 # error
# or they can set both explicitly
file_length:
  warning: 1200
  error: 1200
# naming rules can set warnings/errors for min_length and max_length
# additionally they can set excluded names
type_name:
  min_length: 4 # only warning
  max_length: # warning and error
    warning: 70
    error: 80
  excluded: 
    - iPhone # excluded via string
    - L
    - GFS
identifier_name:
  min_length: # only min_length
    error: 4 # only error
  excluded: # excluded via string array
    - id
    - URL
    - GlobalAPIKey
    - GFS
reporter: "xcode" # reporter type (xcode, json, csv, checkstyle, junit, html, emoji)
cyclomatic_complexity: 20
large_tuple: 3
